export const collegeData = [
  {
    id: 1,
    name: "Indian Institute of Technology Delhi",
    location: "New Delhi",
    state: "Delhi",
    type: "Central University",
    fees: 200000,
    rating: 4.8,
    reviews: 1250,
    students: 8500,
    hasHostel: true,
    streams: ["Engineering", "Science", "Management"],
    features: [
      "NIRF Ranking #2 in Engineering",
      "100% Placement Rate",
      "World-class Research Facilities",
      "International Exchange Programs",
      "Industry Partnerships",
    ],
    coordinates: { lat: 28.6139, lng: 77.209 },
  },
  {
    id: 2,
    name: "All India Institute of Medical Sciences",
    location: "New Delhi",
    state: "Delhi",
    type: "Central University",
    fees: 150000,
    rating: 4.9,
    reviews: 980,
    students: 3200,
    hasHostel: true,
    streams: ["Medical", "Nursing", "Pharmacy"],
    features: [
      "Top Medical College in India",
      "Advanced Medical Equipment",
      "Research Excellence",
      "Super Specialty Departments",
      "International Recognition",
    ],
    coordinates: { lat: 28.5672, lng: 77.21 },
  },
  {
    id: 3,
    name: "University of Mumbai",
    location: "Mumbai",
    state: "Maharashtra",
    type: "State University",
    fees: 80000,
    rating: 4.3,
    reviews: 2100,
    students: 45000,
    hasHostel: false,
    streams: ["Arts", "Science", "Commerce", "Law", "Engineering"],
    features: [
      "Historic Institution (1857)",
      "Multiple Campus Locations",
      "Diverse Course Offerings",
      "Strong Alumni Network",
      "Industry Connections",
    ],
    coordinates: { lat: 19.076, lng: 72.8777 },
  },
  {
    id: 4,
    name: "Indian Institute of Science",
    location: "Bangalore",
    state: "Karnataka",
    type: "Central University",
    fees: 180000,
    rating: 4.7,
    reviews: 750,
    students: 4500,
    hasHostel: true,
    streams: ["Science", "Engineering", "Management"],
    features: [
      "Premier Research Institution",
      "NIRF Ranking #1 Overall",
      "Cutting-edge Laboratories",
      "PhD Programs Excellence",
      "International Collaborations",
    ],
    coordinates: { lat: 13.0827, lng: 77.5718 },
  },
  {
    id: 5,
    name: "Jawaharlal Nehru University",
    location: "New Delhi",
    state: "Delhi",
    type: "Central University",
    fees: 60000,
    rating: 4.4,
    reviews: 1800,
    students: 8200,
    hasHostel: true,
    streams: ["Arts", "Science", "Social Sciences", "Languages"],
    features: [
      "Beautiful Campus",
      "Strong Liberal Arts Program",
      "Diverse Student Community",
      "Research Excellence",
      "Cultural Activities",
    ],
    coordinates: { lat: 28.5383, lng: 77.1641 },
  },
  {
    id: 6,
    name: "Indian Statistical Institute",
    location: "Kolkata",
    state: "West Bengal",
    type: "Central University",
    fees: 120000,
    rating: 4.6,
    reviews: 420,
    students: 1800,
    hasHostel: true,
    streams: ["Science", "Statistics", "Computer Science"],
    features: [
      "Statistics Excellence",
      "Research Focus",
      "Small Class Sizes",
      "Industry Projects",
      "International Recognition",
    ],
    coordinates: { lat: 22.5726, lng: 88.3639 },
  },
  {
    id: 7,
    name: "Banaras Hindu University",
    location: "Varanasi",
    state: "Uttar Pradesh",
    type: "Central University",
    fees: 70000,
    rating: 4.2,
    reviews: 3200,
    students: 28000,
    hasHostel: true,
    streams: ["Arts", "Science", "Engineering", "Medical", "Agriculture"],
    features: [
      "Largest Residential University",
      "Rich Cultural Heritage",
      "Multiple Faculties",
      "Sports Excellence",
      "Alumni Network",
    ],
    coordinates: { lat: 25.2677, lng: 82.9913 },
  },
  {
    id: 8,
    name: "Anna University",
    location: "Chennai",
    state: "Tamil Nadu",
    type: "State University",
    fees: 90000,
    rating: 4.1,
    reviews: 2800,
    students: 35000,
    hasHostel: true,
    streams: ["Engineering", "Technology", "Architecture"],
    features: [
      "Technical Education Leader",
      "Industry Partnerships",
      "Research Centers",
      "Innovation Hub",
      "Placement Support",
    ],
    coordinates: { lat: 13.0827, lng: 80.2707 },
  },
  {
    id: 9,
    name: "Aligarh Muslim University",
    location: "Aligarh",
    state: "Uttar Pradesh",
    type: "Central University",
    fees: 65000,
    rating: 4.0,
    reviews: 2500,
    students: 28500,
    hasHostel: true,
    streams: ["Arts", "Science", "Engineering", "Medical", "Law"],
    features: [
      "Historic Institution",
      "Diverse Programs",
      "Cultural Diversity",
      "Sports Facilities",
      "Alumni Achievement",
    ],
    coordinates: { lat: 27.8974, lng: 78.088 },
  },
  {
    id: 10,
    name: "University of Hyderabad",
    location: "Hyderabad",
    state: "Andhra Pradesh",
    type: "Central University",
    fees: 75000,
    rating: 4.3,
    reviews: 1200,
    students: 5500,
    hasHostel: true,
    streams: ["Arts", "Science", "Social Sciences", "Management"],
    features: ["Research University", "Green Campus", "PhD Programs", "International Students", "Academic Excellence"],
    coordinates: { lat: 17.4569, lng: 78.3302 },
  },
]
